
version: "3.8"
services: 
  server:
         image: image-api-golang-fx
         ports:
            - 8080:8080
        # network_mode: "host"
        #  env_file:
        #     - ./config/.dev.env
         depends_on:
           - db 
         networks:
           - prod
  db:
    image: mysql:8.0
    container_name: db
    ports: 
      - 3307:3306
    environment:       
      - MYSQL_USER=daiana2
      - MYSQL_PASSWORD=12345
      - MYSQL_DATABASE=db_client
      - MYSQL_ROOT_PASSWORD=12345
    networks:
      - prod
  prometheus:
         image: prom/prometheus
         volumes:
            - ./util/observability/prometheus/:/etc/prometheus/
         command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
         ports:
            - 9090:9090
         networks:
             - prod
  grafana:
        image: grafana/grafana
        ports:
           - 3001:3000
        volumes:
           - ./util/observability/grafana/:/etc/grafana/provisioning
        environment:
          - GF_SECURITY_ADMIN_PASSWORD=admin
        networks:
           - prod
  
networks:
  prod:
    # driver: bridge

   
      
















