// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import domain "golang-uber-fx/core/domain"
import dto "golang-uber-fx/core/dto"
import mock "github.com/stretchr/testify/mock"

// IClientService is an autogenerated mock type for the IClientService type
type IClientService struct {
	mock.Mock
}

// DeleteClient provides a mock function with given fields: cpf
func (_m *IClientService) DeleteClient(cpf string) error {
	ret := _m.Called(cpf)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(cpf)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindClient provides a mock function with given fields: cpf
func (_m *IClientService) FindClient(cpf string) (*dto.ClientDtoResponse, error) {
	ret := _m.Called(cpf)

	var r0 *dto.ClientDtoResponse
	if rf, ok := ret.Get(0).(func(string) *dto.ClientDtoResponse); ok {
		r0 = rf(cpf)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.ClientDtoResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(cpf)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveClient provides a mock function with given fields: cliente
func (_m *IClientService) SaveClient(cliente *domain.Client) error {
	ret := _m.Called(cliente)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Client) error); ok {
		r0 = rf(cliente)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
