// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import domain "golang-uber-fx/core/domain"
import mock "github.com/stretchr/testify/mock"

// IUserService is an autogenerated mock type for the IUserService type
type IUserService struct {
	mock.Mock
}

// FindUser provides a mock function with given fields: name
func (_m *IUserService) FindUser(name string) (*domain.User, error) {
	ret := _m.Called(name)

	var r0 *domain.User
	if rf, ok := ret.Get(0).(func(string) *domain.User); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveUser provides a mock function with given fields: user
func (_m *IUserService) SaveUser(user *domain.User) error {
	ret := _m.Called(user)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
