// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import domain "golang-uber-fx/core/domain"
import mock "github.com/stretchr/testify/mock"

// IClientRepository is an autogenerated mock type for the IClientRepository type
type IClientRepository struct {
	mock.Mock
}

// DeleteClient provides a mock function with given fields: cpf
func (_m *IClientRepository) DeleteClient(cpf string) error {
	ret := _m.Called(cpf)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(cpf)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindClient provides a mock function with given fields: cpf
func (_m *IClientRepository) FindClient(cpf string) (*domain.Client, error) {
	ret := _m.Called(cpf)

	var r0 *domain.Client
	if rf, ok := ret.Get(0).(func(string) *domain.Client); ok {
		r0 = rf(cpf)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Client)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(cpf)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveClient provides a mock function with given fields: client
func (_m *IClientRepository) SaveClient(client *domain.Client) error {
	ret := _m.Called(client)

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Client) error); ok {
		r0 = rf(client)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
